// Data from the console's CPU to display
export struct CpuData {
    pbr: string,
    pc: string,
    a: string,
    b: string,
    c: string,
    x: string,
    xl: string,
    xh: string,
    y: string,
    yl: string,
    yh: string,
    d: string,
    dl: string,
    dh: string,
    dbr: string,
    sp: string,
    // Status Register
    p: string,
    // Status Register Flags
    p_c: string,
    p_z: string,
    p_n: string,
    p_d: string,
    p_i: string,
    p_m: string,
    p_v: string,
    p_e: string,
    p_xb: string
}
export struct PpuData {
    vblank: string,
    forced_blanking: string,
    brightness: string,
    bg_mode: string,
    bg3_prio: string,
    mosaic_size: string,
    vram_inc_mode: string,
    vram_inc_amt: string,
    vram_addr: string,
    cgram_addr: string,
}
// Data from the console
export struct ConsoleData {
    cpu: CpuData,
    ppu: PpuData,
}
