// Data from the console's CPU to display
export struct CpuData {
    pbr: string,
    pc: string,
    a: string,
    b: string,
    c: string,
    x: string,
    xl: string,
    xh: string,
    y: string,
    yl: string,
    yh: string,
    d: string,
    dl: string,
    dh: string,
    dbr: string,
    sp: string,
    // Status Register
    p: string,
    // Status Register Flags
    p_c: string,
    p_z: string,
    p_n: string,
    p_d: string,
    p_i: string,
    p_m: string,
    p_v: string,
    p_e: string,
    p_xb: string
}
