// Data from the console's CPU to display
export struct CpuData {
    pbr: int,
    pc: int,
    a: int,
    b: int,
    c: int,
    x: int,
    xl: int,
    xh: int,
    y: int,
    yl: int,
    yh: int,
    d: int,
    dl: int,
    dh: int,
    dbr: int,
    s: int,
    // Status Register
    p: string,
    // Status Register Flags
    p_c: string,
    p_z: string,
    p_n: string,
    p_d: string,
    p_i: string,
    p_m: string,
    p_v: string,
    p_e: string,
    p_xb: string
}
