import { ComboBox, Button, CheckBox, TabWidget } from "std-widgets.slint";
import { Palette } from "../palette.slint";

// Types of binary data sources
export enum BinaryDataSourceType {
    Wram,
    Vram,
    Cgram,
    Cartridge
}
// All the information required to display a block of binary data, except the data itself
export struct BinaryDataSource {
    ramType: BinaryDataSourceType,
    page_offset: int,
    show_as_tile: bool,
    bpp: int,
    palette_index: int,
}
/*
 * View Binary data as a table of bytes
 */
export component BinaryData {
    // The binary data to display, as hex strings
    in property <[[string]]> data;
    // The binary data to display, as an image
    in property <image> data_image;
    // The headers of the columns, including the top-left cell
    in property <[string]> column_headers;
    // The headers of the rows, excluding the top-left cell
    in property <[string]> row_headers;
    // The number of pages to show
    in property <int> num_pages;
    property <int> num_palettes: 64;
    property <int> tab_index;
    // The source of the data, i.e. what ram (WRAM, VRAM) is being displayed
    in-out property <BinaryDataSource> source;
    changed tab_index => {
        source.show-as-tile = tab_index == 1;
        source.palette-index = 0;
    }
    init => {
        source = {
            ramType: BinaryDataSourceType.Wram,
            page_offset: 0,
            show_as_tile: false,
            bpp: 2,
            palette_index: 0
        };
    }

    function set_bpp(bpp: int) {
        source.page-offset = floor(source.page-offset * source.bpp / bpp);
        source.bpp = bpp;
        if (source.bpp == 2) {
            num_palettes = 64;
        } else if (source.bpp == 4) {
            num_palettes = 16;
        } else {
            num_palettes = 1;
        }
        source.palette-index = clamp(source.palette-index, 0, num_palettes - 1);
    }

    function header_color() -> color {
        if (source.ramType == BinaryDataSourceType.Wram) {
            return Palette.blue;
        } else if (source.ramType == BinaryDataSourceType.Vram) {
            return Palette.red;
        } else if (source.ramType == BinaryDataSourceType.Cgram) {
            return Palette.green;
        } else if (source.ramType == BinaryDataSourceType.Cartridge) {
            return Palette.orange;
        }
        return Colors.white;
    }

    function change_page(amount: int) {
        source.page-offset = clamp(0, source.page-offset + amount, num_pages - 1);
    }

    VerticalLayout {
        HorizontalLayout {
            alignment: start;
            ComboBox {
                model: ["WRAM", "VRAM", "CGRAM", "Cartridge"];
                selected(value) => {
                    if (value == "WRAM") {
                        source.ramType = BinaryDataSourceType.Wram
                    } else if (value == "VRAM") {
                        source.ramType = BinaryDataSourceType.Vram
                    } else if (value == "CGRAM") {
                        source.ramType = BinaryDataSourceType.Cgram
                    } else if (value == "Cartridge") {
                        source.ramType = BinaryDataSourceType.Cartridge
                    }
                    source.page-offset = 0;
                }
            }

            Button {
                text: "-16";
                clicked => {
                    change_page(-16)
                }
                enabled: source.page-offset >= 16;
            }

            Button {
                text: "-1";
                clicked => {
                    change_page(-1);
                }
                enabled: source.page-offset != 0;
            }

            // Required for padding
            VerticalLayout {
                padding-left: 10px;
                padding-right: 10px;
                Text {
                    text: "Page " + source.page-offset;
                    vertical-alignment: center;
                }
            }

            Button {
                text: "+1";
                clicked => {
                    change_page(1)
                }
                enabled: source.page-offset != num_pages - 1;
            }

            Button {
                text: "+16";
                clicked => {
                    change_page(16)
                }
                enabled: source.page-offset < num_pages - 16;
            }

            ComboBox {
                model: ["2BPP", "4BPP", "8BPP"];
                selected(value) => {
                    if (value == "2BPP") {
                        set_bpp(2);
                    } else if (value == "4BPP") {
                        set_bpp(4);
                    } else if (value == "8BPP") {
                        set_bpp(8);
                    }
                }
            }

            Button {
                text: "-1";
                clicked => {
                    source.palette_index = max(source.palette_index - 1, 0);
                }
            }

            VerticalLayout {
                alignment: center;
                Text {
                    text: "Palette " + source.palette_index;
                }
            }

            Button {
                text: "+1";
                clicked => {
                    source.palette_index = min(source.palette_index + 1, num_palettes - 1);
                }
            }
        }

        TabWidget {
            current-index <=> tab_index;
            Tab {
                title: "Data";
                GridLayout {
                    padding: 10px;
                    Row {
                        for header[j] in column_headers: Text {
                            text: header;
                            color: header_color();
                            font-weight: FontWeight.bold;
                            horizontal-alignment: j == 0 ? left : right;
                        }
                    }

                    for row_data[i] in data: Row {
                        Text {
                            text: row_headers[i];
                            color: header_color();
                            horizontal-alignment: left;
                        }

                        for byte[j] in row_data: Text {
                            text: byte;
                            color: byte == "00" ? #AAA : #FFF;
                            horizontal-alignment: right;
                        }
                    }
                }
            }

            Tab {
                title: "Tiles";
                Image {
                    source: data_image;
                    image-rendering: ImageRendering.pixelated;
                    width: 100%;
                    height: 100%;
                }
            }
        }
    }
}
