import { Button, Slider, CheckBox } from "std-widgets.slint";
import { Settings } from "../structs/settings.slint";

export component Controls {
    in-out property <Settings> settings;
    callback advance_instruction;
    callback advance_frame;
    callback reset;

    VerticalLayout {
        HorizontalLayout {
            spacing: 5px;
            Button {
                text: "Reset";
                clicked => {
                    reset()
                };
            }

            Button {
                text: settings.is-paused ? "Play" : "Pause";
                clicked => {
                    settings.is-paused = !settings.is-paused
                }
            }

            Button {
                text: "1 INST";
                clicked => advance_instruction();
            }

            Button {
                text: "1 FRAME";
                clicked => advance_frame();
            }

            Slider {
                value <=> settings.volume;
            }
        }

        HorizontalLayout {
            CheckBox {
                checked <=> settings.log_cpu;
                text: "Log CPU";
            }

            CheckBox {
                checked <=> settings.log_apu;
                text: "Log APU";
            }
        }
    }
}
