import { CpuData } from "../structs/cpu_data.slint";
import { VerticalBox, StandardTableView, Button } from "std-widgets.slint";
import { Palette } from "../palette.slint";
import { Register } from "./register.slint";
import { HighLowRegister } from "./high_low_register.slint";


export component CpuDisplay {
    in property <CpuData> data;

    VerticalLayout {
        alignment: start;
        spacing: 5px;
        padding: 10px;
        vertical-stretch: 0;
        Register {
            name: "PBR";
            value: data.pbr;
        }

        Register {
            name: "PC";
            value: data.pc;
        }

        HighLowRegister {
            name: "C";
            value: data.c;
            low: data.a;
            high: data.b;
        }

        HighLowRegister {
            name: "X";
            value: data.x;
            low: data.xl;
            high: data.xh;
        }

        HighLowRegister {
            name: "Y";
            value: data.y;
            low: data.yl;
            high: data.yh;
        }

        Register {
            name: "SP";
            value: data.sp;
        }

        Register {
            name: "DBR";
            value: data.dbr;
        }

        HighLowRegister {
            name: "D";
            value: data.d;
            low: data.dl;
            high: data.dh;
        }

        Register {
            name: "P";
            value: data.p;
            for flag in [
                { name: "P.n", value: data.p_n },
                { name: "P.v", value: data.p_v },
                { name: "P.m", value: data.p_m },
                { name: "P.xb", value: data.p_xb },
                { name: "P.d", value: data.p_d },
                { name: "P.i", value: data.p_i },
                { name: "P.z", value: data.p_z },
                { name: "P.c", value: data.p_c },
            ]: Register {
                name: flag.name;
                value: flag.value;
                headerColor: Palette.secondaryHeader;
            }
        }
    }
}
