import { DisassemblyLine } from "../structs/disassembly_line.slint";
import { Palette } from "../palette.slint";

// Show the disassembly information
export component Disassembly {
    in property <[DisassemblyLine]> lines;
    in property <color> pc_color;

    height: 100%;

    VerticalLayout {
        padding: 5px;
        alignment: start;
        for line[i] in lines: HorizontalLayout {
            alignment: start;
            width: 150px;
            spacing: 10px;

            Text {
                text: line.pc + ":";
                color: pc_color;
            }

            Text {
                text: line.instruction;
                color: line.is_current ? Palette.white : Palette.light_grey;
            }

            Text {
                text: line.arguments;
                color: line.is_current ? Palette.white : Palette.light_grey;
            }
        }
    }
}
