import { Register } from "./register.slint";
import { Palette } from "../palette.slint";

export component HighLowRegister {
    in property <string> name;
    in property <string> value;
    in property <string> low;
    in property <string> high;
    in property <color> primaryHeader;
    in property <color> secondaryHeader;
    property <bool> is_open;
    VerticalLayout {
        Register {
            name: name;
            value: value;
            headerColor <=> primaryHeader;
            Register {
                name: name + "l";
                value: low;
                headerColor <=> primaryHeader;
            }

            Register {
                name: name + "h";
                value: high;
                headerColor <=> primaryHeader;
            }
        }
    }
}
