import { Register } from "./register.slint";
import { Palette } from "../palette.slint";
import { Fmt } from "../globals.slint";

export component HighLowRegister {
    in property <string> name;
    in property <int> value;
    in property <int> low;
    in property <int> high;
    in property <color> primaryHeader;
    in property <color> secondaryHeader;
    property <bool> is_open;
    VerticalLayout {
        Register {
            name: name;
            value: Fmt.word(value);
            headerColor <=> primaryHeader;
            Register {
                name: name + "l";
                value: Fmt.byte(low);
                headerColor <=> primaryHeader;
            }

            Register {
                name: name + "h";
                value: Fmt.byte(high);
                headerColor <=> primaryHeader;
            }
        }
    }
}
