import { Register } from "register.slint";
import { RegisterList } from "register_list.slint";
import { Fmt } from "../globals.slint";
import { Palette } from "../palette.slint";
import { ScrollView } from "std-widgets.slint";


export struct OamData {
    x: int,
    y: int,
    tile_index: int,
    tile_addr: int,
    name_select: int,
    flip_x: bool,
    flip_y: bool,
    priority: int,
    palette_index: int,
    size_select: int,
    msb_x: bool,
    // The tile, rendered to an image
    tile: image
}

export component OamDisplay inherits ScrollView {
    height: 100%;
    width: 300px;
    in property <[OamData]> data;

    GridLayout {
        padding: 5px;
        spacing: 1px;
        Row {
            for header in ["X", "Y", "#", "Addr", "NS", "PRI", "PAL", "TILE"]: Text {
                text: header;
            }
        }

        for d[i] in data: Row {
            Text {
                vertical-alignment: center;
                text: Fmt.byte(d.x);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.byte(d.y);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.address(d.tile_index);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.address(d.tile_addr);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.flag(d.name_select == 1);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.byte(d.priority);
            }

            Text {
                vertical-alignment: center;
                text: Fmt.byte(d.palette_index);
            }

            Image {
                source: d.tile;
                image-rendering: pixelated;
                min-width: 50px;
                min-height: 50px;
            }
        }
    }
}
