import { Register } from "./register.slint";

export struct RegisterData { name: string, value: string}


// Renders a list of Registers
export component RegisterList {
    in property <[RegisterData]> registers;
    in property <color> headerColor;
    // By default consume all height
    height: 100%;

    VerticalLayout {
        alignment: start;
        spacing: 5px;
        padding: 10px;
        vertical-stretch: 0;

        for register[i] in registers: Register {
            headerColor: headerColor;
            name: register.name;
            value: register.value;
        }
    }
}
