import { Palette } from "../palette.slint";

// Component to show a register value in a row
export component Register {
    in property <string> name;
    in property <string> value;
    in property <color> headerColor;
    VerticalLayout {
        HorizontalLayout {
            alignment: space-between;
            spacing: 20px;
            Text {
                text: name;
                font-weight: 900;
                color: headerColor;
            }

            Text {
                text: value;
            }
        }

        VerticalLayout {
            padding-left: 5px;
            @children
        }
    }
}
