[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
super-yane = { path = "../core" }
wdc65816 = { path = "../wdc65816" }
spc700 = { path = "../spc700" }
log = { workspace = true }
simplelog = "0.12.2"
itertools = "0.14.0"
rfd = "0.15.3"
wavers = "1.5.1"
derive-new = "0.7.0"
serde-brief = { version = "0.2.0", features = ["alloc"] }
slint = "1.16.0"
rodio = "0.22.2"
closure = "0.3.0"
eframe = "0.35.0"
egui = { version = "0.35.0", features = ["color-hex"] }
egui_dock = "0.20.1"
egui_infinite_scroll = "0.11.0"
strum = "0.28.0"
rand = "0.10.2"
muda = "0.19.3"
egui_extras = "0.35.0"

[build-dependencies]
slint-build = "1.14.1"
