import { StandardController } from "standard_controller.slint";

export component AppWindow inherits Window {
    // The RGB data from the emulator
    in property <image> pixel_data;
    out property <StandardController> controller;
    callback advance_emulator;
    forward-focus: scope;
    Timer {
        interval: 16ms;
        triggered => {
            advance_emulator();
        }
    }

    Text {
        color: green;
        text: "Hello World!";
    }

    function handle_key_change(key: string, value: bool) {
        if (key == "w") {
            controller.up = value;
        } else if (key == "a") {
            controller.left = value;
        } else if (key == "s") {
            controller.down = value;
        } else if (key == "d") {
            controller.right = value;
        } else if (key == "r") {
            controller.start = value;
        } else if (key == "f") {
            controller.select = value;
        } else if (key == "q") {
            controller.l = value;
        } else if (key == "e") {
            controller.r = value;
        } else if (key == " ") {
            controller.b = value;
        } else if (key == "b") {
            controller.a = value;
        } else if (key == "n") {
            controller.y = value;
        } else if (key == "m") {
            controller.x = value;
        }
    }

    scope := FocusScope {
        key-pressed(event) => {
            handle_key_change(event.text, true);
            accept
        }

        key-released(event) => {
            handle_key_change(event.text, false);
            accept
        }

        Image {
            source: pixel_data;
        }
    }
}
