import {
    Slider,
    ProgressIndicator,
    Button,
    CheckBox,
    HorizontalBox,
} from "std-widgets.slint";
import {
    StandardControllerInput,
} from "components/standard_controller_input.slint";
import { Settings } from "structs/settings.slint";
import { StandardController } from "structs/standard_controller.slint";


export component AppWindow inherits Window {
    // The RGB data from the emulator
    in property <image> pixel_data;

    // The settings
    out property <Settings> settings;
    callback settings_changed(Settings);
    changed settings => {
        settings_changed(settings);
    }
    // The controllers, separate so that we are not copying all the settings every keypress
    out property <StandardController> controller;
    callback controller_changed(StandardController);
    changed controller => {
        controller_changed(controller)
    }

    init => {
        settings.volume = 50.0;
    }

    forward-focus: scope;

    Text {
        color: green;
        text: "Hello World!";
    }

    scope := FocusScope {
        key-pressed(event) => {
            controller_input.handle_key_change(event.text, true);
            accept
        }

        key-released(event) => {
            controller_input.handle_key_change(event.text, false);
            accept
        }

        controller_input := StandardControllerInput {
            controller <=> controller;
        }

        VerticalLayout {
            Image {
                source: pixel_data;
                width: 800px;
                height: 600px;
            }

            HorizontalBox {
                padding: 5px;
                Slider {
                    value <=> settings.volume;
                }

                CheckBox {
                    text: "Pause";
                    checked <=> settings.is-paused;
                }
            }
        }
    }
}
