import {
    Slider,
    ProgressIndicator,
    Button,
    CheckBox,
    HorizontalBox,
    TabWidget,
} from "std-widgets.slint";
import {
    StandardControllerInput,
} from "components/standard_controller_input.slint";
import { Settings } from "structs/settings.slint";
import { StandardController } from "structs/standard_controller.slint";
import { ConsoleData } from "structs/console_data.slint";
import { CpuDisplay } from "components/cpu_display.slint";
import { ApuData } from "structs/apu_data.slint";
import "fonts/KodeMono-VariableFont_wght.ttf";
import { PpuDisplay } from "components/ppu_display.slint";
import { ApuDisplay } from "components/apu_display.slint";
import { Disassembly } from "components/disassembly.slint";
import { DisassemblyLine } from "structs/disassembly_line.slint";
import { BackgroundData } from "structs/background_data.slint";
import { Controls } from "components/controls.slint";
import { BinaryData, BinaryDataSrc } from "components/binary_data.slint";
import { ExternalFunction } from "./globals.slint";
import { Backgrounds } from "components/backgrounds.slint";

export { ExternalFunction }

export component AppWindow inherits Window {
    // The RGB data from the emulator
    in property <image> pixel_data;
    // The console data from the emulator
    in property <ConsoleData> console_data;
    // The lines to display
    in property <[DisassemblyLine]> disassembly_lines;
    // Binary data to display
    in property <[[int]]> binary_data <=> binary_viewer.data;
    in property <image> binary_image <=> binary_viewer.data_image;
    out property <int> binary_data_offset: binary_viewer.offset;
    in property <int> binary_data_len <=> binary_viewer.data_len;
    out property <BinaryDataSrc> binary_src <=> binary_viewer.data_src;
    out property <int> bpp <=> binary_viewer.bpp;
    out property <int> palette_index <=> binary_viewer.palette_index;
    in property <[BackgroundData]> backgrounds;

    callback advance_instructions(int);
    callback advance_frames(int);
    callback reset();
    callback load_rom();
    callback load_savestate();
    callback save_savestate();

    // The settings
    out property <Settings> settings;
    callback settings_changed(Settings);
    changed settings => {
        settings_changed(settings);
    }
    // The controllers, separate so that we are not copying all the settings every keypress
    out property <StandardController> controller;
    callback controller_changed(StandardController);
    changed controller => {
        controller_changed(controller)
    }
    forward-focus: scope;

    title: "Super Y.A.N.E";

    default-font-family: "Kode Mono";

    MenuBar {
        Menu {
            title: @tr("File");
            Menu {
                title: @tr("Load");

                MenuItem {
                    title: @tr("ROM");
                    activated => {
                        load_rom();
                    }
                }

                MenuItem {
                    title: @tr("State");
                    activated => {
                        load_savestate();
                    }
                }
            }

            Menu {
                title: @tr("Save");
                MenuItem {
                    title: @tr("State");
                    activated => {
                        save_savestate();
                    }
                }
            }
        }
    }

    scope := FocusScope {
        key-pressed(event) => {
            controller_input.handle_key_change(event.text, true);
            accept
        }

        key-released(event) => {
            controller_input.handle_key_change(event.text, false);
            accept
        }

        controller_input := StandardControllerInput {
            controller <=> controller;
        }

        VerticalLayout {
            height: 100%;
            alignment: stretch;
            HorizontalLayout {
                vertical-stretch: 1;
                alignment: stretch;
                TabWidget {
                    horizontal-stretch: 0;
                    Tab {
                        title: "CPU";
                        CpuDisplay {
                            height: 100%;
                            width: 100%;
                            data: console_data.cpu;
                        }
                    }

                    Tab {
                        title: "PPU";
                        PpuDisplay {
                            height: 100%;
                            width: 100%;
                            data: console_data.ppu;
                        }
                    }

                    Tab {
                        title: "APU";
                        ApuDisplay {
                            data: console_data.apu;
                            width: 100%;
                            height: 100%;
                        }
                    }

                    Tab {
                        title: "DMA";
                    }

                    Tab {
                        title: "BGs";
                        Backgrounds {
                            height: 100%;
                            width: 100%;
                            backgrounds <=> backgrounds;
                        }
                    }
                }

                Rectangle {
                    background: black;
                    horizontal-stretch: 1;
                    VerticalLayout {
                        alignment: center;
                        Image {
                            horizontal-stretch: 1;
                            source: pixel_data;
                            min-width: 600px;
                        }

                        Rectangle {
                            horizontal-stretch: 0;
                            background: #444;
                            Controls {
                                width: 100%;
                                settings <=> settings;
                                advance_frame => {
                                    advance_frames(1);
                                }
                                advance_instruction => {
                                    advance_instructions(1);
                                }
                                reset => {
                                    reset();
                                }
                            }
                        }
                    }
                }

                TabWidget {
                    horizontal-stretch: 0;
                    Tab {
                        title: "CPU";
                        Disassembly {
                            lines: disassembly_lines;
                        }
                    }

                    Tab {
                        title: "APU";
                    }
                }
            }

            HorizontalLayout {
                vertical-stretch: 0;
                binary_viewer := BinaryData { }
            }
        }
    }
}
