// Globally used colors
export global Palette {
    in-out property <color> primaryText: white;
    in-out property <color> primaryHeader: #d77aff;
    in-out property <color> secondaryHeader: #a463bf;
    in-out property <color> wramHeader: #5bb9eb;
    in-out property <color> vramHeader: #5dd463;
    in-out property <color> cgramHeader: #d14757;
    in-out property <color> cartridgeHeader:#bf6336;
}
