// Globally used colors
export global Palette {
    in-out property <color> primaryText: white;
    // Constant colors
    in-out property <color> blue: #5bb9eb;
    in-out property <color> red: #d14757;
    in-out property <color> green: #5dd463;
    in-out property <color> orange: #bf6336;
    in-out property <color> purple: #ab62e3;
    in-out property <color> light_grey: #AAA;
    in-out property <color> white: #FFF;
    // Colors assigned to roles
    in-out property <color> cpu: red;
    in-out property <color> ppu: green;
    in-out property <color> apu: blue;
    in-out property <color> cartridge: orange;
}
